### ISSUE TITLE
pip install lightning failed

### ISSUE THREAD

**Issue by happybeta** [git-men/lightning#5]
> 
C:\Users\> pip install lightning
WARNING: Ignoring invalid distribution -yyaml (c:\python37\lib\site-packages)
WARNING: Ignoring invalid distribution -ikpi-hita-swta (c:\python37\lib\site-packages)
WARNING: Ignoring invalid distribution -yyaml (c:\python37\lib\site-packages)
WARNING: Ignoring invalid distribution -ikpi-hita-swta (c:\python37\lib\site-packages)
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
ERROR: Could not find a version that satisfies the requirement lightning (from versions: none)
ERROR: No matching distribution found for `lightning`

**Comment by qwIvan** [comment]
Run `pip install django-lightning` instead.
